version: '3.1'
services:

  wordpress:
    links:
      - mysql
    build:
      context: ./wordpress
    image: dkr.demar.ee/dd-wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example

  frontend:
    build: "./frontend"
    ports:
      - 3000:3000
    environment:
      POSTS_API: "https://wp.demar.ee"
    volumes:
      - "./frontend:/home/nodejs/app"