version: '3.1'
services:

  wordpress:
    links:
      - mysql
    build:
      context: ./wordpress
    image: dkr.demar.ee/dd-wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      ASSET_HOST: "${ASSET_HOST}"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example

  frontend:
    links:
      - wordpress
    build: "./frontend"
    ports:
      - 3000:3000
    environment:
      POSTS_API: "http://wordpress"
    volumes:
      - "./frontend:/home/nodejs/app"

  # assets:
  #   build: "./wordpress/wp-content/themes/birthdaysuit"
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - "./wordpress/wp-content/themes/birthdaysuit:/app"
  #   working_dir: "/app"
  #   command:
  #     - "/app/node_modules/.bin/webpack-dev-server"
  #     - --inline
  #     - --hot
