version: '3.1'
services:
  frontend:
    build: "."
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      POSTS_API: "https://wp.demar.ee"
    volumes:
      - "${ROOT_PATH:-.}:/home/nodejs/app"
      - "node-modules:/home/nodejs/app/node_modules"
volumes:
  node-modules: