version: '3.1'
services:
  frontend:
    links:
      - wordpress
    build: "./frontend"
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      POSTS_API: "http://wordpress"
      POSTS_CLIENT_API: "http://localhost:8080"
    volumes:
      - "./frontend:/home/nodejs/app"

  wordpress:
    links:
      - mysql
    build:
      context: ./wordpress
    image: dkr.demar.ee/dd-wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080
    volumes:
      - "./wordpress/themes/birthdaysuit:/var/www/html/wp-content/themes/birthdaysuit"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    ports:
      - 3307:3306
    volumes:
      - "./sqls:/docker-entrypoint-initdb.d"
